services:
  web:
    build: .
    command: >
      sh -c "chown -R 1000:1000 /app/src/static &&
             python manage.py collectstatic --noinput &&
             uvicorn src.sync.asgi:application --host 0.0.0.0 --port 8000 --log-level debug --lifespan off --timeout-keep-alive 300"
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - redis
      - db
      - rabbitmq
    env_file:
      - .env
    user: "1000:1000"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  celery:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             celery -A src.sync worker -l INFO --concurrency=4 --pool=prefork"
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
      - rabbitmq
    env_file:
      - .env
    user: "1000:1000"
    restart: unless-stopped

  celery-beat:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             celery -A src.sync beat -l INFO"
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
      - rabbitmq
    env_file:
      - .env
    user: "1000:1000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/src/static
    command: >
      sh -c "chown -R 1000:1000 /app/src/static && nginx -g 'daemon off;'"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  static_volume:
    driver: local
    driver_opts:
      type: none
      device: ./src/static
