# Generated by Django 5.2 on 2025-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="spotify_access_token",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="spotify_refresh_token",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
