# Generated by Django 5.2

from django.db import migrations, models

from apps.accounts.crypto import EncryptedTextField


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_spotify_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="spotify_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="spotify_access_token",
            field=EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="spotify_refresh_token",
            field=EncryptedTextField(blank=True, default=""),
        ),
    ]
