# Generated by Django 5.2 on 2025-04-23 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_playlist_url", models.URLField()),
                (
                    "spotify_playlist_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("spotify_playlist_name", models.CharField(max_length=255)),
                ("reverse_order", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_video_id", models.CharField(max_length=255)),
                ("youtube_video_title", models.CharField(max_length=255)),
                ("original_artist", models.CharField(max_length=255)),
                ("original_song", models.CharField(max_length=255)),
                ("spotify_track_id", models.CharField(max_length=255)),
                ("spotify_track_name", models.CharField(max_length=255)),
                ("spotify_artist_name", models.CharField(max_length=255)),
                ("confidence_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sync_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_mappings",
                        to="playlist_sync.syncjob",
                    ),
                ),
            ],
        ),
    ]
