# Generated by Django 5.2 on 2025-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlist_sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
