# Generated by Django 5.2

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.ids


def fill_idempotency_keys(apps, schema_editor):
    SyncJob = apps.get_model("playlist_sync", "SyncJob")
    for job in SyncJob.objects.all():
        job.idempotency_key = uuid.uuid4().hex
        job.save(update_fields=["idempotency_key"])



class Migration(migrations.Migration):
    dependencies = [
        ("playlist_sync", "0002_syncjob_task_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="syncjob",
            name="cancel_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="classifier_prompt_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="correlation_id",
            field=models.CharField(default=core.ids.new_correlation_id, max_length=36),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="estimated_cost_usd",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="idempotency_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="progress_current",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="progress_stage",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="progress_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="provider_requests",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="source_kind",
            field=models.CharField(default="playlist", max_length=20),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="spotify_write_checkpoint",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="syncjob",
            name="tokens_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="spotify_playlist_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("classifying", "Classifying"),
                    ("awaiting_review", "Awaiting review"),
                    ("applying", "Applying"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="task_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="syncjob",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trackmapping",
            name="classification",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="trackmapping",
            name="classifier_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="trackmapping",
            name="decision",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposed"),
                    ("needs_review", "Needs review"),
                    ("skipped", "Skipped"),
                    ("unmatched", "Unmatched"),
                    ("confirmed", "Confirmed"),
                    ("excluded", "Excluded"),
                    ("written", "Written"),
                ],
                default="proposed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trackmapping",
            name="skip_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="trackmapping",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trackmapping",
            name="original_artist",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="trackmapping",
            name="original_song",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="trackmapping",
            name="spotify_artist_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="trackmapping",
            name="spotify_track_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="trackmapping",
            name="spotify_track_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="trackmapping",
            name="youtube_video_id",
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name="ClassificationCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cache_key", models.CharField(max_length=64, unique=True)),
                ("youtube_video_id", models.CharField(max_length=32)),
                ("normalised_title", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("classifier_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name="classificationcache",
            index=models.Index(fields=["expires_at"], name="playlist_sy_expires_ae946e_idx"),
        ),
        migrations.AddIndex(
            model_name="syncjob",
            index=models.Index(fields=["user", "status"], name="playlist_sy_user_id_aeebc0_idx"),
        ),
        migrations.AddIndex(
            model_name="syncjob",
            index=models.Index(fields=["created_at"], name="playlist_sy_created_0c1a5f_idx"),
        ),
        migrations.RunPython(fill_idempotency_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="syncjob",
            name="idempotency_key",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="syncjob",
            constraint=models.UniqueConstraint(fields=("user", "idempotency_key"), name="unique_user_idempotency"),
        ),
        migrations.AddConstraint(
            model_name="trackmapping",
            constraint=models.UniqueConstraint(fields=("sync_job", "youtube_video_id"), name="unique_job_video"),
        ),
    ]
